'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace SiswaServiceReference
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SiswaModel", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class SiswaModel
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private IDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AgamaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AlamatField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AlamatOrangTuaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmailField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private JenisKelaminField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private KodePosField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private KodePosOrangTuaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private KotaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private KotaOrangTuaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NamaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NamaAyahField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NamaIbuField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NamaSMPAsalField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NoHPField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NoHPOrangTuaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NoTelephoneField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NoTelephoneOrangTuaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PenjurusanField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TempatLahirField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PhotoField() As Byte
        
        Private TanggalLahirField As Date
        
        Private TanggalMasukField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NISField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ID() As Integer
            Get
                Return Me.IDField
            End Get
            Set
                If (Me.IDField.Equals(value) <> true) Then
                    Me.IDField = value
                    Me.RaisePropertyChanged("ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property Agama() As String
            Get
                Return Me.AgamaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AgamaField, value) <> true) Then
                    Me.AgamaField = value
                    Me.RaisePropertyChanged("Agama")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property Alamat() As String
            Get
                Return Me.AlamatField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AlamatField, value) <> true) Then
                    Me.AlamatField = value
                    Me.RaisePropertyChanged("Alamat")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property AlamatOrangTua() As String
            Get
                Return Me.AlamatOrangTuaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AlamatOrangTuaField, value) <> true) Then
                    Me.AlamatOrangTuaField = value
                    Me.RaisePropertyChanged("AlamatOrangTua")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property Email() As String
            Get
                Return Me.EmailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmailField, value) <> true) Then
                    Me.EmailField = value
                    Me.RaisePropertyChanged("Email")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Property JenisKelamin() As String
            Get
                Return Me.JenisKelaminField
            End Get
            Set
                If (Object.ReferenceEquals(Me.JenisKelaminField, value) <> true) Then
                    Me.JenisKelaminField = value
                    Me.RaisePropertyChanged("JenisKelamin")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Property KodePos() As String
            Get
                Return Me.KodePosField
            End Get
            Set
                If (Object.ReferenceEquals(Me.KodePosField, value) <> true) Then
                    Me.KodePosField = value
                    Me.RaisePropertyChanged("KodePos")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public Property KodePosOrangTua() As String
            Get
                Return Me.KodePosOrangTuaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.KodePosOrangTuaField, value) <> true) Then
                    Me.KodePosOrangTuaField = value
                    Me.RaisePropertyChanged("KodePosOrangTua")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public Property Kota() As String
            Get
                Return Me.KotaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.KotaField, value) <> true) Then
                    Me.KotaField = value
                    Me.RaisePropertyChanged("Kota")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=9)>  _
        Public Property KotaOrangTua() As String
            Get
                Return Me.KotaOrangTuaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.KotaOrangTuaField, value) <> true) Then
                    Me.KotaOrangTuaField = value
                    Me.RaisePropertyChanged("KotaOrangTua")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=10)>  _
        Public Property Nama() As String
            Get
                Return Me.NamaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NamaField, value) <> true) Then
                    Me.NamaField = value
                    Me.RaisePropertyChanged("Nama")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=11)>  _
        Public Property NamaAyah() As String
            Get
                Return Me.NamaAyahField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NamaAyahField, value) <> true) Then
                    Me.NamaAyahField = value
                    Me.RaisePropertyChanged("NamaAyah")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=12)>  _
        Public Property NamaIbu() As String
            Get
                Return Me.NamaIbuField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NamaIbuField, value) <> true) Then
                    Me.NamaIbuField = value
                    Me.RaisePropertyChanged("NamaIbu")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=13)>  _
        Public Property NamaSMPAsal() As String
            Get
                Return Me.NamaSMPAsalField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NamaSMPAsalField, value) <> true) Then
                    Me.NamaSMPAsalField = value
                    Me.RaisePropertyChanged("NamaSMPAsal")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=14)>  _
        Public Property NoHP() As String
            Get
                Return Me.NoHPField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NoHPField, value) <> true) Then
                    Me.NoHPField = value
                    Me.RaisePropertyChanged("NoHP")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=15)>  _
        Public Property NoHPOrangTua() As String
            Get
                Return Me.NoHPOrangTuaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NoHPOrangTuaField, value) <> true) Then
                    Me.NoHPOrangTuaField = value
                    Me.RaisePropertyChanged("NoHPOrangTua")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=16)>  _
        Public Property NoTelephone() As String
            Get
                Return Me.NoTelephoneField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NoTelephoneField, value) <> true) Then
                    Me.NoTelephoneField = value
                    Me.RaisePropertyChanged("NoTelephone")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=17)>  _
        Public Property NoTelephoneOrangTua() As String
            Get
                Return Me.NoTelephoneOrangTuaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NoTelephoneOrangTuaField, value) <> true) Then
                    Me.NoTelephoneOrangTuaField = value
                    Me.RaisePropertyChanged("NoTelephoneOrangTua")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=18)>  _
        Public Property Penjurusan() As String
            Get
                Return Me.PenjurusanField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PenjurusanField, value) <> true) Then
                    Me.PenjurusanField = value
                    Me.RaisePropertyChanged("Penjurusan")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=19)>  _
        Public Property TempatLahir() As String
            Get
                Return Me.TempatLahirField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TempatLahirField, value) <> true) Then
                    Me.TempatLahirField = value
                    Me.RaisePropertyChanged("TempatLahir")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=20)>  _
        Public Property Photo() As Byte()
            Get
                Return Me.PhotoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PhotoField, value) <> true) Then
                    Me.PhotoField = value
                    Me.RaisePropertyChanged("Photo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=21)>  _
        Public Property TanggalLahir() As Date
            Get
                Return Me.TanggalLahirField
            End Get
            Set
                If (Me.TanggalLahirField.Equals(value) <> true) Then
                    Me.TanggalLahirField = value
                    Me.RaisePropertyChanged("TanggalLahir")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=22)>  _
        Public Property TanggalMasuk() As Date
            Get
                Return Me.TanggalMasukField
            End Get
            Set
                If (Me.TanggalMasukField.Equals(value) <> true) Then
                    Me.TanggalMasukField = value
                    Me.RaisePropertyChanged("TanggalMasuk")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=23)>  _
        Public Property NIS() As String
            Get
                Return Me.NISField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NISField, value) <> true) Then
                    Me.NISField = value
                    Me.RaisePropertyChanged("NIS")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="SiswaServiceReference.MasterSiswaServiceSoap")>  _
    Public Interface MasterSiswaServiceSoap
        
        'CODEGEN: Generating message contract since element name model from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SaveSiswa", ReplyAction:="*")>  _
        Function SaveSiswa(ByVal request As SiswaServiceReference.SaveSiswaRequest) As SiswaServiceReference.SaveSiswaResponse
        
        'CODEGEN: Generating message contract since element name model from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UpdateSiswa", ReplyAction:="*")>  _
        Function UpdateSiswa(ByVal request As SiswaServiceReference.UpdateSiswaRequest) As SiswaServiceReference.UpdateSiswaResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/DeleteSiswa", ReplyAction:="*")>  _
        Sub DeleteSiswa(ByVal siswaid As Integer)
        
        'CODEGEN: Generating message contract since element name GetListSiswaResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetListSiswa", ReplyAction:="*")>  _
        Function GetListSiswa(ByVal request As SiswaServiceReference.GetListSiswaRequest) As SiswaServiceReference.GetListSiswaResponse
        
        'CODEGEN: Generating message contract since element name nama from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetListByName", ReplyAction:="*")>  _
        Function GetListByName(ByVal request As SiswaServiceReference.GetListByNameRequest) As SiswaServiceReference.GetListByNameResponse
        
        'CODEGEN: Generating message contract since element name nis from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetListByNis", ReplyAction:="*")>  _
        Function GetListByNis(ByVal request As SiswaServiceReference.GetListByNisRequest) As SiswaServiceReference.GetListByNisResponse
        
        'CODEGEN: Generating message contract since element name GetSiswaResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetSiswa", ReplyAction:="*")>  _
        Function GetSiswa(ByVal request As SiswaServiceReference.GetSiswaRequest) As SiswaServiceReference.GetSiswaResponse
        
        'CODEGEN: Generating message contract since element name tahun from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetSiswaByJurusan", ReplyAction:="*")>  _
        Function GetSiswaByJurusan(ByVal request As SiswaServiceReference.GetSiswaByJurusanRequest) As SiswaServiceReference.GetSiswaByJurusanResponse
        
        'CODEGEN: Generating message contract since element name tahun from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetSiswaByTahunAngkatan", ReplyAction:="*")>  _
        Function GetSiswaByTahunAngkatan(ByVal request As SiswaServiceReference.GetSiswaByTahunAngkatanRequest) As SiswaServiceReference.GetSiswaByTahunAngkatanResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SaveSiswaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SaveSiswa", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SiswaServiceReference.SaveSiswaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SiswaServiceReference.SaveSiswaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SaveSiswaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public model As SiswaServiceReference.SiswaModel
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal model As SiswaServiceReference.SiswaModel)
            MyBase.New
            Me.model = model
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SaveSiswaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SaveSiswaResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SiswaServiceReference.SaveSiswaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SiswaServiceReference.SaveSiswaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class SaveSiswaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UpdateSiswaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UpdateSiswa", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SiswaServiceReference.UpdateSiswaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SiswaServiceReference.UpdateSiswaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class UpdateSiswaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public model As SiswaServiceReference.SiswaModel
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal model As SiswaServiceReference.SiswaModel)
            MyBase.New
            Me.model = model
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UpdateSiswaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UpdateSiswaResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SiswaServiceReference.UpdateSiswaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SiswaServiceReference.UpdateSiswaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class UpdateSiswaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetListSiswaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetListSiswa", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SiswaServiceReference.GetListSiswaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SiswaServiceReference.GetListSiswaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class GetListSiswaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetListSiswaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetListSiswaResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SiswaServiceReference.GetListSiswaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SiswaServiceReference.GetListSiswaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetListSiswaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetListSiswaResult() As SiswaServiceReference.SiswaModel
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetListSiswaResult() As SiswaServiceReference.SiswaModel)
            MyBase.New
            Me.GetListSiswaResult = GetListSiswaResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetListByNameRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetListByName", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SiswaServiceReference.GetListByNameRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SiswaServiceReference.GetListByNameRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetListByNameRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public nama As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nama As String)
            MyBase.New
            Me.nama = nama
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetListByNameResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetListByNameResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SiswaServiceReference.GetListByNameResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SiswaServiceReference.GetListByNameResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetListByNameResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetListByNameResult() As SiswaServiceReference.SiswaModel
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetListByNameResult() As SiswaServiceReference.SiswaModel)
            MyBase.New
            Me.GetListByNameResult = GetListByNameResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetListByNisRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetListByNis", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SiswaServiceReference.GetListByNisRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SiswaServiceReference.GetListByNisRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetListByNisRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public nis As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nis As String)
            MyBase.New
            Me.nis = nis
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetListByNisResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetListByNisResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SiswaServiceReference.GetListByNisResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SiswaServiceReference.GetListByNisResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetListByNisResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetListByNisResult() As SiswaServiceReference.SiswaModel
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetListByNisResult() As SiswaServiceReference.SiswaModel)
            MyBase.New
            Me.GetListByNisResult = GetListByNisResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetSiswaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetSiswa", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SiswaServiceReference.GetSiswaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SiswaServiceReference.GetSiswaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetSiswaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public recordId As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal recordId As Integer)
            MyBase.New
            Me.recordId = recordId
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetSiswaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetSiswaResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SiswaServiceReference.GetSiswaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SiswaServiceReference.GetSiswaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetSiswaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetSiswaResult As SiswaServiceReference.SiswaModel
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetSiswaResult As SiswaServiceReference.SiswaModel)
            MyBase.New
            Me.GetSiswaResult = GetSiswaResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetSiswaByJurusanRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetSiswaByJurusan", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SiswaServiceReference.GetSiswaByJurusanRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SiswaServiceReference.GetSiswaByJurusanRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetSiswaByJurusanRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public tahun As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public jurusan As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public tahunajaran As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal tahun As String, ByVal jurusan As String, ByVal tahunajaran As Integer)
            MyBase.New
            Me.tahun = tahun
            Me.jurusan = jurusan
            Me.tahunajaran = tahunajaran
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetSiswaByJurusanResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetSiswaByJurusanResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SiswaServiceReference.GetSiswaByJurusanResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SiswaServiceReference.GetSiswaByJurusanResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetSiswaByJurusanResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetSiswaByJurusanResult() As SiswaServiceReference.SiswaModel
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetSiswaByJurusanResult() As SiswaServiceReference.SiswaModel)
            MyBase.New
            Me.GetSiswaByJurusanResult = GetSiswaByJurusanResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetSiswaByTahunAngkatanRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetSiswaByTahunAngkatan", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SiswaServiceReference.GetSiswaByTahunAngkatanRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SiswaServiceReference.GetSiswaByTahunAngkatanRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetSiswaByTahunAngkatanRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public tahun As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal tahun As String)
            MyBase.New
            Me.tahun = tahun
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetSiswaByTahunAngkatanResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetSiswaByTahunAngkatanResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SiswaServiceReference.GetSiswaByTahunAngkatanResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SiswaServiceReference.GetSiswaByTahunAngkatanResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetSiswaByTahunAngkatanResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetSiswaByTahunAngkatanResult() As SiswaServiceReference.SiswaModel
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetSiswaByTahunAngkatanResult() As SiswaServiceReference.SiswaModel)
            MyBase.New
            Me.GetSiswaByTahunAngkatanResult = GetSiswaByTahunAngkatanResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface MasterSiswaServiceSoapChannel
        Inherits SiswaServiceReference.MasterSiswaServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class MasterSiswaServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of SiswaServiceReference.MasterSiswaServiceSoap)
        Implements SiswaServiceReference.MasterSiswaServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SiswaServiceReference_MasterSiswaServiceSoap_SaveSiswa(ByVal request As SiswaServiceReference.SaveSiswaRequest) As SiswaServiceReference.SaveSiswaResponse Implements SiswaServiceReference.MasterSiswaServiceSoap.SaveSiswa
            Return MyBase.Channel.SaveSiswa(request)
        End Function
        
        Public Sub SaveSiswa(ByVal model As SiswaServiceReference.SiswaModel)
            Dim inValue As SiswaServiceReference.SaveSiswaRequest = New SiswaServiceReference.SaveSiswaRequest()
            inValue.Body = New SiswaServiceReference.SaveSiswaRequestBody()
            inValue.Body.model = model
            Dim retVal As SiswaServiceReference.SaveSiswaResponse = CType(Me,SiswaServiceReference.MasterSiswaServiceSoap).SaveSiswa(inValue)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SiswaServiceReference_MasterSiswaServiceSoap_UpdateSiswa(ByVal request As SiswaServiceReference.UpdateSiswaRequest) As SiswaServiceReference.UpdateSiswaResponse Implements SiswaServiceReference.MasterSiswaServiceSoap.UpdateSiswa
            Return MyBase.Channel.UpdateSiswa(request)
        End Function
        
        Public Sub UpdateSiswa(ByVal model As SiswaServiceReference.SiswaModel)
            Dim inValue As SiswaServiceReference.UpdateSiswaRequest = New SiswaServiceReference.UpdateSiswaRequest()
            inValue.Body = New SiswaServiceReference.UpdateSiswaRequestBody()
            inValue.Body.model = model
            Dim retVal As SiswaServiceReference.UpdateSiswaResponse = CType(Me,SiswaServiceReference.MasterSiswaServiceSoap).UpdateSiswa(inValue)
        End Sub
        
        Public Sub DeleteSiswa(ByVal siswaid As Integer) Implements SiswaServiceReference.MasterSiswaServiceSoap.DeleteSiswa
            MyBase.Channel.DeleteSiswa(siswaid)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SiswaServiceReference_MasterSiswaServiceSoap_GetListSiswa(ByVal request As SiswaServiceReference.GetListSiswaRequest) As SiswaServiceReference.GetListSiswaResponse Implements SiswaServiceReference.MasterSiswaServiceSoap.GetListSiswa
            Return MyBase.Channel.GetListSiswa(request)
        End Function
        
        Public Function GetListSiswa() As SiswaServiceReference.SiswaModel()
            Dim inValue As SiswaServiceReference.GetListSiswaRequest = New SiswaServiceReference.GetListSiswaRequest()
            inValue.Body = New SiswaServiceReference.GetListSiswaRequestBody()
            Dim retVal As SiswaServiceReference.GetListSiswaResponse = CType(Me,SiswaServiceReference.MasterSiswaServiceSoap).GetListSiswa(inValue)
            Return retVal.Body.GetListSiswaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SiswaServiceReference_MasterSiswaServiceSoap_GetListByName(ByVal request As SiswaServiceReference.GetListByNameRequest) As SiswaServiceReference.GetListByNameResponse Implements SiswaServiceReference.MasterSiswaServiceSoap.GetListByName
            Return MyBase.Channel.GetListByName(request)
        End Function
        
        Public Function GetListByName(ByVal nama As String) As SiswaServiceReference.SiswaModel()
            Dim inValue As SiswaServiceReference.GetListByNameRequest = New SiswaServiceReference.GetListByNameRequest()
            inValue.Body = New SiswaServiceReference.GetListByNameRequestBody()
            inValue.Body.nama = nama
            Dim retVal As SiswaServiceReference.GetListByNameResponse = CType(Me,SiswaServiceReference.MasterSiswaServiceSoap).GetListByName(inValue)
            Return retVal.Body.GetListByNameResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SiswaServiceReference_MasterSiswaServiceSoap_GetListByNis(ByVal request As SiswaServiceReference.GetListByNisRequest) As SiswaServiceReference.GetListByNisResponse Implements SiswaServiceReference.MasterSiswaServiceSoap.GetListByNis
            Return MyBase.Channel.GetListByNis(request)
        End Function
        
        Public Function GetListByNis(ByVal nis As String) As SiswaServiceReference.SiswaModel()
            Dim inValue As SiswaServiceReference.GetListByNisRequest = New SiswaServiceReference.GetListByNisRequest()
            inValue.Body = New SiswaServiceReference.GetListByNisRequestBody()
            inValue.Body.nis = nis
            Dim retVal As SiswaServiceReference.GetListByNisResponse = CType(Me,SiswaServiceReference.MasterSiswaServiceSoap).GetListByNis(inValue)
            Return retVal.Body.GetListByNisResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SiswaServiceReference_MasterSiswaServiceSoap_GetSiswa(ByVal request As SiswaServiceReference.GetSiswaRequest) As SiswaServiceReference.GetSiswaResponse Implements SiswaServiceReference.MasterSiswaServiceSoap.GetSiswa
            Return MyBase.Channel.GetSiswa(request)
        End Function
        
        Public Function GetSiswa(ByVal recordId As Integer) As SiswaServiceReference.SiswaModel
            Dim inValue As SiswaServiceReference.GetSiswaRequest = New SiswaServiceReference.GetSiswaRequest()
            inValue.Body = New SiswaServiceReference.GetSiswaRequestBody()
            inValue.Body.recordId = recordId
            Dim retVal As SiswaServiceReference.GetSiswaResponse = CType(Me,SiswaServiceReference.MasterSiswaServiceSoap).GetSiswa(inValue)
            Return retVal.Body.GetSiswaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SiswaServiceReference_MasterSiswaServiceSoap_GetSiswaByJurusan(ByVal request As SiswaServiceReference.GetSiswaByJurusanRequest) As SiswaServiceReference.GetSiswaByJurusanResponse Implements SiswaServiceReference.MasterSiswaServiceSoap.GetSiswaByJurusan
            Return MyBase.Channel.GetSiswaByJurusan(request)
        End Function
        
        Public Function GetSiswaByJurusan(ByVal tahun As String, ByVal jurusan As String, ByVal tahunajaran As Integer) As SiswaServiceReference.SiswaModel()
            Dim inValue As SiswaServiceReference.GetSiswaByJurusanRequest = New SiswaServiceReference.GetSiswaByJurusanRequest()
            inValue.Body = New SiswaServiceReference.GetSiswaByJurusanRequestBody()
            inValue.Body.tahun = tahun
            inValue.Body.jurusan = jurusan
            inValue.Body.tahunajaran = tahunajaran
            Dim retVal As SiswaServiceReference.GetSiswaByJurusanResponse = CType(Me,SiswaServiceReference.MasterSiswaServiceSoap).GetSiswaByJurusan(inValue)
            Return retVal.Body.GetSiswaByJurusanResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SiswaServiceReference_MasterSiswaServiceSoap_GetSiswaByTahunAngkatan(ByVal request As SiswaServiceReference.GetSiswaByTahunAngkatanRequest) As SiswaServiceReference.GetSiswaByTahunAngkatanResponse Implements SiswaServiceReference.MasterSiswaServiceSoap.GetSiswaByTahunAngkatan
            Return MyBase.Channel.GetSiswaByTahunAngkatan(request)
        End Function
        
        Public Function GetSiswaByTahunAngkatan(ByVal tahun As String) As SiswaServiceReference.SiswaModel()
            Dim inValue As SiswaServiceReference.GetSiswaByTahunAngkatanRequest = New SiswaServiceReference.GetSiswaByTahunAngkatanRequest()
            inValue.Body = New SiswaServiceReference.GetSiswaByTahunAngkatanRequestBody()
            inValue.Body.tahun = tahun
            Dim retVal As SiswaServiceReference.GetSiswaByTahunAngkatanResponse = CType(Me,SiswaServiceReference.MasterSiswaServiceSoap).GetSiswaByTahunAngkatan(inValue)
            Return retVal.Body.GetSiswaByTahunAngkatanResult
        End Function
    End Class
End Namespace
