'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5420
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

<Assembly: Global.System.Data.Objects.DataClasses.EdmSchemaAttribute("f4a3fa5f-f4dd-40c7-aaa0-e7b4e78d82b2")> 

'Original file name:
'Generation date: 3/29/2013 4:56:47 PM
'''<summary>
'''There are no comments for SiakSmanEntities in the schema.
'''</summary>
Partial Public Class SiakSmanEntities
    Inherits Global.System.Data.Objects.ObjectContext
    '''<summary>
    '''Initializes a new SiakSmanEntities object using the connection string found in the 'SiakSmanEntities' section of the application configuration file.
    '''</summary>
    Public Sub New()
        MyBase.New("name=SiakSmanEntities", "SiakSmanEntities")
        Me.OnContextCreated
    End Sub
    '''<summary>
    '''Initialize a new SiakSmanEntities object.
    '''</summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "SiakSmanEntities")
        Me.OnContextCreated
    End Sub
    '''<summary>
    '''Initialize a new SiakSmanEntities object.
    '''</summary>
    Public Sub New(ByVal connection As Global.System.Data.EntityClient.EntityConnection)
        MyBase.New(connection, "SiakSmanEntities")
        Me.OnContextCreated
    End Sub
    Partial Private Sub OnContextCreated()
        End Sub
    '''<summary>
    '''There are no comments for MasterGuru in the schema.
    '''</summary>
    Public ReadOnly Property MasterGuru() As Global.System.Data.Objects.ObjectQuery(Of MasterGuru)
        Get
            If (Me._MasterGuru Is Nothing) Then
                Me._MasterGuru = MyBase.CreateQuery(Of MasterGuru)("[MasterGuru]")
            End If
            Return Me._MasterGuru
        End Get
    End Property
    Private _MasterGuru As Global.System.Data.Objects.ObjectQuery(Of MasterGuru)
    '''<summary>
    '''There are no comments for MasterKaryawan in the schema.
    '''</summary>
    Public ReadOnly Property MasterKaryawan() As Global.System.Data.Objects.ObjectQuery(Of MasterKaryawan)
        Get
            If (Me._MasterKaryawan Is Nothing) Then
                Me._MasterKaryawan = MyBase.CreateQuery(Of MasterKaryawan)("[MasterKaryawan]")
            End If
            Return Me._MasterKaryawan
        End Get
    End Property
    Private _MasterKaryawan As Global.System.Data.Objects.ObjectQuery(Of MasterKaryawan)
    '''<summary>
    '''There are no comments for MasterSiswa in the schema.
    '''</summary>
    Public ReadOnly Property MasterSiswa() As Global.System.Data.Objects.ObjectQuery(Of MasterSiswa)
        Get
            If (Me._MasterSiswa Is Nothing) Then
                Me._MasterSiswa = MyBase.CreateQuery(Of MasterSiswa)("[MasterSiswa]")
            End If
            Return Me._MasterSiswa
        End Get
    End Property
    Private _MasterSiswa As Global.System.Data.Objects.ObjectQuery(Of MasterSiswa)
    '''<summary>
    '''There are no comments for MasterGuru in the schema.
    '''</summary>
    Public Sub AddToMasterGuru(ByVal masterGuru As MasterGuru)
        MyBase.AddObject("MasterGuru", masterGuru)
    End Sub
    '''<summary>
    '''There are no comments for MasterKaryawan in the schema.
    '''</summary>
    Public Sub AddToMasterKaryawan(ByVal masterKaryawan As MasterKaryawan)
        MyBase.AddObject("MasterKaryawan", masterKaryawan)
    End Sub
    '''<summary>
    '''There are no comments for MasterSiswa in the schema.
    '''</summary>
    Public Sub AddToMasterSiswa(ByVal masterSiswa As MasterSiswa)
        MyBase.AddObject("MasterSiswa", masterSiswa)
    End Sub
End Class
'''<summary>
'''There are no comments for SiakSmanModel.MasterGuru in the schema.
'''</summary>
'''<KeyProperties>
'''ID
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="SiakSmanModel", Name:="MasterGuru"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class MasterGuru
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''Create a new MasterGuru object.
    '''</summary>
    '''<param name="id">Initial value of ID.</param>
    '''<param name="nIP">Initial value of NIP.</param>
    '''<param name="guruID">Initial value of GuruID.</param>
    '''<param name="nama">Initial value of Nama.</param>
    '''<param name="jenisKelamin">Initial value of JenisKelamin.</param>
    '''<param name="tanggalLahir">Initial value of TanggalLahir.</param>
    Public Shared Function CreateMasterGuru(ByVal id As Integer, ByVal nIP As String, ByVal guruID As String, ByVal nama As String, ByVal jenisKelamin As String, ByVal tanggalLahir As Date) As MasterGuru
        Dim masterGuru As MasterGuru = New MasterGuru
        masterGuru.ID = id
        masterGuru.NIP = nIP
        masterGuru.GuruID = guruID
        masterGuru.Nama = nama
        masterGuru.JenisKelamin = jenisKelamin
        masterGuru.TanggalLahir = tanggalLahir
        Return masterGuru
    End Function
    '''<summary>
    '''There are no comments for Property ID in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property ID() As Integer
        Get
            Return Me._ID
        End Get
        Set
            Me.OnIDChanging(value)
            Me.ReportPropertyChanging("ID")
            Me._ID = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("ID")
            Me.OnIDChanged
        End Set
    End Property
    Private _ID As Integer
    Partial Private Sub OnIDChanging(ByVal value As Integer)
        End Sub
    Partial Private Sub OnIDChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property NIP in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property NIP() As String
        Get
            Return Me._NIP
        End Get
        Set
            Me.OnNIPChanging(value)
            Me.ReportPropertyChanging("NIP")
            Me._NIP = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("NIP")
            Me.OnNIPChanged
        End Set
    End Property
    Private _NIP As String
    Partial Private Sub OnNIPChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnNIPChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property GuruID in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property GuruID() As String
        Get
            Return Me._GuruID
        End Get
        Set
            Me.OnGuruIDChanging(value)
            Me.ReportPropertyChanging("GuruID")
            Me._GuruID = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("GuruID")
            Me.OnGuruIDChanged
        End Set
    End Property
    Private _GuruID As String
    Partial Private Sub OnGuruIDChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnGuruIDChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Nama in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Nama() As String
        Get
            Return Me._Nama
        End Get
        Set
            Me.OnNamaChanging(value)
            Me.ReportPropertyChanging("Nama")
            Me._Nama = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Nama")
            Me.OnNamaChanged
        End Set
    End Property
    Private _Nama As String
    Partial Private Sub OnNamaChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnNamaChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property JenisKelamin in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property JenisKelamin() As String
        Get
            Return Me._JenisKelamin
        End Get
        Set
            Me.OnJenisKelaminChanging(value)
            Me.ReportPropertyChanging("JenisKelamin")
            Me._JenisKelamin = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("JenisKelamin")
            Me.OnJenisKelaminChanged
        End Set
    End Property
    Private _JenisKelamin As String
    Partial Private Sub OnJenisKelaminChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnJenisKelaminChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property TempatLahir in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property TempatLahir() As String
        Get
            Return Me._TempatLahir
        End Get
        Set
            Me.OnTempatLahirChanging(value)
            Me.ReportPropertyChanging("TempatLahir")
            Me._TempatLahir = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("TempatLahir")
            Me.OnTempatLahirChanged
        End Set
    End Property
    Private _TempatLahir As String
    Partial Private Sub OnTempatLahirChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnTempatLahirChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property TanggalLahir in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property TanggalLahir() As Date
        Get
            Return Me._TanggalLahir
        End Get
        Set
            Me.OnTanggalLahirChanging(value)
            Me.ReportPropertyChanging("TanggalLahir")
            Me._TanggalLahir = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("TanggalLahir")
            Me.OnTanggalLahirChanged
        End Set
    End Property
    Private _TanggalLahir As Date
    Partial Private Sub OnTanggalLahirChanging(ByVal value As Date)
        End Sub
    Partial Private Sub OnTanggalLahirChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Agama in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Agama() As String
        Get
            Return Me._Agama
        End Get
        Set
            Me.OnAgamaChanging(value)
            Me.ReportPropertyChanging("Agama")
            Me._Agama = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Agama")
            Me.OnAgamaChanged
        End Set
    End Property
    Private _Agama As String
    Partial Private Sub OnAgamaChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnAgamaChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Email in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Email() As String
        Get
            Return Me._Email
        End Get
        Set
            Me.OnEmailChanging(value)
            Me.ReportPropertyChanging("Email")
            Me._Email = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Email")
            Me.OnEmailChanged
        End Set
    End Property
    Private _Email As String
    Partial Private Sub OnEmailChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnEmailChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Alamat in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Alamat() As String
        Get
            Return Me._Alamat
        End Get
        Set
            Me.OnAlamatChanging(value)
            Me.ReportPropertyChanging("Alamat")
            Me._Alamat = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Alamat")
            Me.OnAlamatChanged
        End Set
    End Property
    Private _Alamat As String
    Partial Private Sub OnAlamatChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnAlamatChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Kota in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Kota() As String
        Get
            Return Me._Kota
        End Get
        Set
            Me.OnKotaChanging(value)
            Me.ReportPropertyChanging("Kota")
            Me._Kota = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Kota")
            Me.OnKotaChanged
        End Set
    End Property
    Private _Kota As String
    Partial Private Sub OnKotaChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnKotaChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property KodePos in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property KodePos() As String
        Get
            Return Me._KodePos
        End Get
        Set
            Me.OnKodePosChanging(value)
            Me.ReportPropertyChanging("KodePos")
            Me._KodePos = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("KodePos")
            Me.OnKodePosChanged
        End Set
    End Property
    Private _KodePos As String
    Partial Private Sub OnKodePosChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnKodePosChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property NoTelephone in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property NoTelephone() As String
        Get
            Return Me._NoTelephone
        End Get
        Set
            Me.OnNoTelephoneChanging(value)
            Me.ReportPropertyChanging("NoTelephone")
            Me._NoTelephone = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("NoTelephone")
            Me.OnNoTelephoneChanged
        End Set
    End Property
    Private _NoTelephone As String
    Partial Private Sub OnNoTelephoneChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnNoTelephoneChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property NoHP in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property NoHP() As String
        Get
            Return Me._NoHP
        End Get
        Set
            Me.OnNoHPChanging(value)
            Me.ReportPropertyChanging("NoHP")
            Me._NoHP = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("NoHP")
            Me.OnNoHPChanged
        End Set
    End Property
    Private _NoHP As String
    Partial Private Sub OnNoHPChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnNoHPChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Photo in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Photo() As Byte()
        Get
            Return Global.System.Data.Objects.DataClasses.StructuralObject.GetValidValue(Me._Photo)
        End Get
        Set
            Me.OnPhotoChanging(value)
            Me.ReportPropertyChanging("Photo")
            Me._Photo = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Photo")
            Me.OnPhotoChanged
        End Set
    End Property
    Private _Photo() As Byte
    Partial Private Sub OnPhotoChanging(ByVal value() As Byte)
        End Sub
    Partial Private Sub OnPhotoChanged()
        End Sub
End Class
'''<summary>
'''There are no comments for SiakSmanModel.MasterKaryawan in the schema.
'''</summary>
'''<KeyProperties>
'''ID
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="SiakSmanModel", Name:="MasterKaryawan"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class MasterKaryawan
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''Create a new MasterKaryawan object.
    '''</summary>
    '''<param name="id">Initial value of ID.</param>
    '''<param name="nIP">Initial value of NIP.</param>
    '''<param name="karyawanID">Initial value of KaryawanID.</param>
    '''<param name="nama">Initial value of Nama.</param>
    '''<param name="jenisKelamin">Initial value of JenisKelamin.</param>
    '''<param name="tanggalLahir">Initial value of TanggalLahir.</param>
    Public Shared Function CreateMasterKaryawan(ByVal id As Integer, ByVal nIP As String, ByVal karyawanID As String, ByVal nama As String, ByVal jenisKelamin As String, ByVal tanggalLahir As Date) As MasterKaryawan
        Dim masterKaryawan As MasterKaryawan = New MasterKaryawan
        masterKaryawan.ID = id
        masterKaryawan.NIP = nIP
        masterKaryawan.KaryawanID = karyawanID
        masterKaryawan.Nama = nama
        masterKaryawan.JenisKelamin = jenisKelamin
        masterKaryawan.TanggalLahir = tanggalLahir
        Return masterKaryawan
    End Function
    '''<summary>
    '''There are no comments for Property ID in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property ID() As Integer
        Get
            Return Me._ID
        End Get
        Set
            Me.OnIDChanging(value)
            Me.ReportPropertyChanging("ID")
            Me._ID = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("ID")
            Me.OnIDChanged
        End Set
    End Property
    Private _ID As Integer
    Partial Private Sub OnIDChanging(ByVal value As Integer)
        End Sub
    Partial Private Sub OnIDChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property NIP in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property NIP() As String
        Get
            Return Me._NIP
        End Get
        Set
            Me.OnNIPChanging(value)
            Me.ReportPropertyChanging("NIP")
            Me._NIP = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("NIP")
            Me.OnNIPChanged
        End Set
    End Property
    Private _NIP As String
    Partial Private Sub OnNIPChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnNIPChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property KaryawanID in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property KaryawanID() As String
        Get
            Return Me._KaryawanID
        End Get
        Set
            Me.OnKaryawanIDChanging(value)
            Me.ReportPropertyChanging("KaryawanID")
            Me._KaryawanID = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("KaryawanID")
            Me.OnKaryawanIDChanged
        End Set
    End Property
    Private _KaryawanID As String
    Partial Private Sub OnKaryawanIDChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnKaryawanIDChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Nama in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Nama() As String
        Get
            Return Me._Nama
        End Get
        Set
            Me.OnNamaChanging(value)
            Me.ReportPropertyChanging("Nama")
            Me._Nama = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Nama")
            Me.OnNamaChanged
        End Set
    End Property
    Private _Nama As String
    Partial Private Sub OnNamaChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnNamaChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property JenisKelamin in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property JenisKelamin() As String
        Get
            Return Me._JenisKelamin
        End Get
        Set
            Me.OnJenisKelaminChanging(value)
            Me.ReportPropertyChanging("JenisKelamin")
            Me._JenisKelamin = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("JenisKelamin")
            Me.OnJenisKelaminChanged
        End Set
    End Property
    Private _JenisKelamin As String
    Partial Private Sub OnJenisKelaminChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnJenisKelaminChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property TempatLahir in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property TempatLahir() As String
        Get
            Return Me._TempatLahir
        End Get
        Set
            Me.OnTempatLahirChanging(value)
            Me.ReportPropertyChanging("TempatLahir")
            Me._TempatLahir = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("TempatLahir")
            Me.OnTempatLahirChanged
        End Set
    End Property
    Private _TempatLahir As String
    Partial Private Sub OnTempatLahirChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnTempatLahirChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property TanggalLahir in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property TanggalLahir() As Date
        Get
            Return Me._TanggalLahir
        End Get
        Set
            Me.OnTanggalLahirChanging(value)
            Me.ReportPropertyChanging("TanggalLahir")
            Me._TanggalLahir = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("TanggalLahir")
            Me.OnTanggalLahirChanged
        End Set
    End Property
    Private _TanggalLahir As Date
    Partial Private Sub OnTanggalLahirChanging(ByVal value As Date)
        End Sub
    Partial Private Sub OnTanggalLahirChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Agama in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Agama() As String
        Get
            Return Me._Agama
        End Get
        Set
            Me.OnAgamaChanging(value)
            Me.ReportPropertyChanging("Agama")
            Me._Agama = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Agama")
            Me.OnAgamaChanged
        End Set
    End Property
    Private _Agama As String
    Partial Private Sub OnAgamaChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnAgamaChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Email in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Email() As String
        Get
            Return Me._Email
        End Get
        Set
            Me.OnEmailChanging(value)
            Me.ReportPropertyChanging("Email")
            Me._Email = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Email")
            Me.OnEmailChanged
        End Set
    End Property
    Private _Email As String
    Partial Private Sub OnEmailChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnEmailChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Alamat in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Alamat() As String
        Get
            Return Me._Alamat
        End Get
        Set
            Me.OnAlamatChanging(value)
            Me.ReportPropertyChanging("Alamat")
            Me._Alamat = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Alamat")
            Me.OnAlamatChanged
        End Set
    End Property
    Private _Alamat As String
    Partial Private Sub OnAlamatChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnAlamatChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Kota in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Kota() As String
        Get
            Return Me._Kota
        End Get
        Set
            Me.OnKotaChanging(value)
            Me.ReportPropertyChanging("Kota")
            Me._Kota = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Kota")
            Me.OnKotaChanged
        End Set
    End Property
    Private _Kota As String
    Partial Private Sub OnKotaChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnKotaChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property KodePos in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property KodePos() As String
        Get
            Return Me._KodePos
        End Get
        Set
            Me.OnKodePosChanging(value)
            Me.ReportPropertyChanging("KodePos")
            Me._KodePos = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("KodePos")
            Me.OnKodePosChanged
        End Set
    End Property
    Private _KodePos As String
    Partial Private Sub OnKodePosChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnKodePosChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property NoTelephone in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property NoTelephone() As String
        Get
            Return Me._NoTelephone
        End Get
        Set
            Me.OnNoTelephoneChanging(value)
            Me.ReportPropertyChanging("NoTelephone")
            Me._NoTelephone = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("NoTelephone")
            Me.OnNoTelephoneChanged
        End Set
    End Property
    Private _NoTelephone As String
    Partial Private Sub OnNoTelephoneChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnNoTelephoneChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property NoHP in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property NoHP() As String
        Get
            Return Me._NoHP
        End Get
        Set
            Me.OnNoHPChanging(value)
            Me.ReportPropertyChanging("NoHP")
            Me._NoHP = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("NoHP")
            Me.OnNoHPChanged
        End Set
    End Property
    Private _NoHP As String
    Partial Private Sub OnNoHPChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnNoHPChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Photo in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Photo() As Byte()
        Get
            Return Global.System.Data.Objects.DataClasses.StructuralObject.GetValidValue(Me._Photo)
        End Get
        Set
            Me.OnPhotoChanging(value)
            Me.ReportPropertyChanging("Photo")
            Me._Photo = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Photo")
            Me.OnPhotoChanged
        End Set
    End Property
    Private _Photo() As Byte
    Partial Private Sub OnPhotoChanging(ByVal value() As Byte)
        End Sub
    Partial Private Sub OnPhotoChanged()
        End Sub
End Class
'''<summary>
'''There are no comments for SiakSmanModel.MasterSiswa in the schema.
'''</summary>
'''<KeyProperties>
'''ID
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="SiakSmanModel", Name:="MasterSiswa"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class MasterSiswa
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''Create a new MasterSiswa object.
    '''</summary>
    '''<param name="id">Initial value of ID.</param>
    '''<param name="nIS">Initial value of NIS.</param>
    '''<param name="nama">Initial value of Nama.</param>
    '''<param name="jenisKelamin">Initial value of JenisKelamin.</param>
    '''<param name="tanggalLahir">Initial value of TanggalLahir.</param>
    '''<param name="tanggalMasuk">Initial value of TanggalMasuk.</param>
    Public Shared Function CreateMasterSiswa(ByVal id As Integer, ByVal nIS As String, ByVal nama As String, ByVal jenisKelamin As String, ByVal tanggalLahir As Date, ByVal tanggalMasuk As Date) As MasterSiswa
        Dim masterSiswa As MasterSiswa = New MasterSiswa
        masterSiswa.ID = id
        masterSiswa.NIS = nIS
        masterSiswa.Nama = nama
        masterSiswa.JenisKelamin = jenisKelamin
        masterSiswa.TanggalLahir = tanggalLahir
        masterSiswa.TanggalMasuk = tanggalMasuk
        Return masterSiswa
    End Function
    '''<summary>
    '''There are no comments for Property ID in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property ID() As Integer
        Get
            Return Me._ID
        End Get
        Set
            Me.OnIDChanging(value)
            Me.ReportPropertyChanging("ID")
            Me._ID = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("ID")
            Me.OnIDChanged
        End Set
    End Property
    Private _ID As Integer
    Partial Private Sub OnIDChanging(ByVal value As Integer)
        End Sub
    Partial Private Sub OnIDChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property NIS in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property NIS() As String
        Get
            Return Me._NIS
        End Get
        Set
            Me.OnNISChanging(value)
            Me.ReportPropertyChanging("NIS")
            Me._NIS = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("NIS")
            Me.OnNISChanged
        End Set
    End Property
    Private _NIS As String
    Partial Private Sub OnNISChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnNISChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Nama in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Nama() As String
        Get
            Return Me._Nama
        End Get
        Set
            Me.OnNamaChanging(value)
            Me.ReportPropertyChanging("Nama")
            Me._Nama = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Nama")
            Me.OnNamaChanged
        End Set
    End Property
    Private _Nama As String
    Partial Private Sub OnNamaChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnNamaChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property JenisKelamin in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property JenisKelamin() As String
        Get
            Return Me._JenisKelamin
        End Get
        Set
            Me.OnJenisKelaminChanging(value)
            Me.ReportPropertyChanging("JenisKelamin")
            Me._JenisKelamin = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("JenisKelamin")
            Me.OnJenisKelaminChanged
        End Set
    End Property
    Private _JenisKelamin As String
    Partial Private Sub OnJenisKelaminChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnJenisKelaminChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property TempatLahir in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property TempatLahir() As String
        Get
            Return Me._TempatLahir
        End Get
        Set
            Me.OnTempatLahirChanging(value)
            Me.ReportPropertyChanging("TempatLahir")
            Me._TempatLahir = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("TempatLahir")
            Me.OnTempatLahirChanged
        End Set
    End Property
    Private _TempatLahir As String
    Partial Private Sub OnTempatLahirChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnTempatLahirChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property TanggalLahir in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property TanggalLahir() As Date
        Get
            Return Me._TanggalLahir
        End Get
        Set
            Me.OnTanggalLahirChanging(value)
            Me.ReportPropertyChanging("TanggalLahir")
            Me._TanggalLahir = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("TanggalLahir")
            Me.OnTanggalLahirChanged
        End Set
    End Property
    Private _TanggalLahir As Date
    Partial Private Sub OnTanggalLahirChanging(ByVal value As Date)
        End Sub
    Partial Private Sub OnTanggalLahirChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Agama in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Agama() As String
        Get
            Return Me._Agama
        End Get
        Set
            Me.OnAgamaChanging(value)
            Me.ReportPropertyChanging("Agama")
            Me._Agama = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Agama")
            Me.OnAgamaChanged
        End Set
    End Property
    Private _Agama As String
    Partial Private Sub OnAgamaChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnAgamaChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Email in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Email() As String
        Get
            Return Me._Email
        End Get
        Set
            Me.OnEmailChanging(value)
            Me.ReportPropertyChanging("Email")
            Me._Email = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Email")
            Me.OnEmailChanged
        End Set
    End Property
    Private _Email As String
    Partial Private Sub OnEmailChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnEmailChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Alamat in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Alamat() As String
        Get
            Return Me._Alamat
        End Get
        Set
            Me.OnAlamatChanging(value)
            Me.ReportPropertyChanging("Alamat")
            Me._Alamat = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Alamat")
            Me.OnAlamatChanged
        End Set
    End Property
    Private _Alamat As String
    Partial Private Sub OnAlamatChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnAlamatChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Kota in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Kota() As String
        Get
            Return Me._Kota
        End Get
        Set
            Me.OnKotaChanging(value)
            Me.ReportPropertyChanging("Kota")
            Me._Kota = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Kota")
            Me.OnKotaChanged
        End Set
    End Property
    Private _Kota As String
    Partial Private Sub OnKotaChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnKotaChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property KodePos in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property KodePos() As String
        Get
            Return Me._KodePos
        End Get
        Set
            Me.OnKodePosChanging(value)
            Me.ReportPropertyChanging("KodePos")
            Me._KodePos = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("KodePos")
            Me.OnKodePosChanged
        End Set
    End Property
    Private _KodePos As String
    Partial Private Sub OnKodePosChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnKodePosChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property NoTelephone in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property NoTelephone() As String
        Get
            Return Me._NoTelephone
        End Get
        Set
            Me.OnNoTelephoneChanging(value)
            Me.ReportPropertyChanging("NoTelephone")
            Me._NoTelephone = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("NoTelephone")
            Me.OnNoTelephoneChanged
        End Set
    End Property
    Private _NoTelephone As String
    Partial Private Sub OnNoTelephoneChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnNoTelephoneChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property NoHP in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property NoHP() As String
        Get
            Return Me._NoHP
        End Get
        Set
            Me.OnNoHPChanging(value)
            Me.ReportPropertyChanging("NoHP")
            Me._NoHP = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("NoHP")
            Me.OnNoHPChanged
        End Set
    End Property
    Private _NoHP As String
    Partial Private Sub OnNoHPChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnNoHPChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property TanggalMasuk in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property TanggalMasuk() As Date
        Get
            Return Me._TanggalMasuk
        End Get
        Set
            Me.OnTanggalMasukChanging(value)
            Me.ReportPropertyChanging("TanggalMasuk")
            Me._TanggalMasuk = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("TanggalMasuk")
            Me.OnTanggalMasukChanged
        End Set
    End Property
    Private _TanggalMasuk As Date
    Partial Private Sub OnTanggalMasukChanging(ByVal value As Date)
        End Sub
    Partial Private Sub OnTanggalMasukChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property NamaSMPAsal in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property NamaSMPAsal() As String
        Get
            Return Me._NamaSMPAsal
        End Get
        Set
            Me.OnNamaSMPAsalChanging(value)
            Me.ReportPropertyChanging("NamaSMPAsal")
            Me._NamaSMPAsal = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("NamaSMPAsal")
            Me.OnNamaSMPAsalChanged
        End Set
    End Property
    Private _NamaSMPAsal As String
    Partial Private Sub OnNamaSMPAsalChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnNamaSMPAsalChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Photo in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Photo() As Byte()
        Get
            Return Global.System.Data.Objects.DataClasses.StructuralObject.GetValidValue(Me._Photo)
        End Get
        Set
            Me.OnPhotoChanging(value)
            Me.ReportPropertyChanging("Photo")
            Me._Photo = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Photo")
            Me.OnPhotoChanged
        End Set
    End Property
    Private _Photo() As Byte
    Partial Private Sub OnPhotoChanging(ByVal value() As Byte)
        End Sub
    Partial Private Sub OnPhotoChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property NamaAyah in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property NamaAyah() As String
        Get
            Return Me._NamaAyah
        End Get
        Set
            Me.OnNamaAyahChanging(value)
            Me.ReportPropertyChanging("NamaAyah")
            Me._NamaAyah = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("NamaAyah")
            Me.OnNamaAyahChanged
        End Set
    End Property
    Private _NamaAyah As String
    Partial Private Sub OnNamaAyahChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnNamaAyahChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property NamaIbu in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property NamaIbu() As String
        Get
            Return Me._NamaIbu
        End Get
        Set
            Me.OnNamaIbuChanging(value)
            Me.ReportPropertyChanging("NamaIbu")
            Me._NamaIbu = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("NamaIbu")
            Me.OnNamaIbuChanged
        End Set
    End Property
    Private _NamaIbu As String
    Partial Private Sub OnNamaIbuChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnNamaIbuChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property AlamatOrangTua in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property AlamatOrangTua() As String
        Get
            Return Me._AlamatOrangTua
        End Get
        Set
            Me.OnAlamatOrangTuaChanging(value)
            Me.ReportPropertyChanging("AlamatOrangTua")
            Me._AlamatOrangTua = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("AlamatOrangTua")
            Me.OnAlamatOrangTuaChanged
        End Set
    End Property
    Private _AlamatOrangTua As String
    Partial Private Sub OnAlamatOrangTuaChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnAlamatOrangTuaChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property KotaOrangTua in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property KotaOrangTua() As String
        Get
            Return Me._KotaOrangTua
        End Get
        Set
            Me.OnKotaOrangTuaChanging(value)
            Me.ReportPropertyChanging("KotaOrangTua")
            Me._KotaOrangTua = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("KotaOrangTua")
            Me.OnKotaOrangTuaChanged
        End Set
    End Property
    Private _KotaOrangTua As String
    Partial Private Sub OnKotaOrangTuaChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnKotaOrangTuaChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property KodePosOrangTua in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property KodePosOrangTua() As String
        Get
            Return Me._KodePosOrangTua
        End Get
        Set
            Me.OnKodePosOrangTuaChanging(value)
            Me.ReportPropertyChanging("KodePosOrangTua")
            Me._KodePosOrangTua = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("KodePosOrangTua")
            Me.OnKodePosOrangTuaChanged
        End Set
    End Property
    Private _KodePosOrangTua As String
    Partial Private Sub OnKodePosOrangTuaChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnKodePosOrangTuaChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property NoTelephoneOrangTua in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property NoTelephoneOrangTua() As String
        Get
            Return Me._NoTelephoneOrangTua
        End Get
        Set
            Me.OnNoTelephoneOrangTuaChanging(value)
            Me.ReportPropertyChanging("NoTelephoneOrangTua")
            Me._NoTelephoneOrangTua = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("NoTelephoneOrangTua")
            Me.OnNoTelephoneOrangTuaChanged
        End Set
    End Property
    Private _NoTelephoneOrangTua As String
    Partial Private Sub OnNoTelephoneOrangTuaChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnNoTelephoneOrangTuaChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property NoHPOrangTua in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property NoHPOrangTua() As String
        Get
            Return Me._NoHPOrangTua
        End Get
        Set
            Me.OnNoHPOrangTuaChanging(value)
            Me.ReportPropertyChanging("NoHPOrangTua")
            Me._NoHPOrangTua = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("NoHPOrangTua")
            Me.OnNoHPOrangTuaChanged
        End Set
    End Property
    Private _NoHPOrangTua As String
    Partial Private Sub OnNoHPOrangTuaChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnNoHPOrangTuaChanged()
        End Sub
End Class
