'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18033
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace GuruServiceReference
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GuruModel", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class GuruModel
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NamaField As String
        
        Private IDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NIPField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private GuruIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private JenisKelaminField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TempatLahirField As String
        
        Private TanggalLahirField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AgamaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmailField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AlamatField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private KotaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private KodePosField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NoTelephoneField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NoHPField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PhotoField() As Byte
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Nama() As String
            Get
                Return Me.NamaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NamaField, value) <> true) Then
                    Me.NamaField = value
                    Me.RaisePropertyChanged("Nama")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=1)>  _
        Public Property ID() As Integer
            Get
                Return Me.IDField
            End Get
            Set
                If (Me.IDField.Equals(value) <> true) Then
                    Me.IDField = value
                    Me.RaisePropertyChanged("ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property NIP() As String
            Get
                Return Me.NIPField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NIPField, value) <> true) Then
                    Me.NIPField = value
                    Me.RaisePropertyChanged("NIP")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property GuruID() As String
            Get
                Return Me.GuruIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.GuruIDField, value) <> true) Then
                    Me.GuruIDField = value
                    Me.RaisePropertyChanged("GuruID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property JenisKelamin() As String
            Get
                Return Me.JenisKelaminField
            End Get
            Set
                If (Object.ReferenceEquals(Me.JenisKelaminField, value) <> true) Then
                    Me.JenisKelaminField = value
                    Me.RaisePropertyChanged("JenisKelamin")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Property TempatLahir() As String
            Get
                Return Me.TempatLahirField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TempatLahirField, value) <> true) Then
                    Me.TempatLahirField = value
                    Me.RaisePropertyChanged("TempatLahir")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=6)>  _
        Public Property TanggalLahir() As Date
            Get
                Return Me.TanggalLahirField
            End Get
            Set
                If (Me.TanggalLahirField.Equals(value) <> true) Then
                    Me.TanggalLahirField = value
                    Me.RaisePropertyChanged("TanggalLahir")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public Property Agama() As String
            Get
                Return Me.AgamaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AgamaField, value) <> true) Then
                    Me.AgamaField = value
                    Me.RaisePropertyChanged("Agama")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public Property Email() As String
            Get
                Return Me.EmailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmailField, value) <> true) Then
                    Me.EmailField = value
                    Me.RaisePropertyChanged("Email")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=9)>  _
        Public Property Alamat() As String
            Get
                Return Me.AlamatField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AlamatField, value) <> true) Then
                    Me.AlamatField = value
                    Me.RaisePropertyChanged("Alamat")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=10)>  _
        Public Property Kota() As String
            Get
                Return Me.KotaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.KotaField, value) <> true) Then
                    Me.KotaField = value
                    Me.RaisePropertyChanged("Kota")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=11)>  _
        Public Property KodePos() As String
            Get
                Return Me.KodePosField
            End Get
            Set
                If (Object.ReferenceEquals(Me.KodePosField, value) <> true) Then
                    Me.KodePosField = value
                    Me.RaisePropertyChanged("KodePos")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=12)>  _
        Public Property NoTelephone() As String
            Get
                Return Me.NoTelephoneField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NoTelephoneField, value) <> true) Then
                    Me.NoTelephoneField = value
                    Me.RaisePropertyChanged("NoTelephone")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=13)>  _
        Public Property NoHP() As String
            Get
                Return Me.NoHPField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NoHPField, value) <> true) Then
                    Me.NoHPField = value
                    Me.RaisePropertyChanged("NoHP")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=14)>  _
        Public Property Photo() As Byte()
            Get
                Return Me.PhotoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PhotoField, value) <> true) Then
                    Me.PhotoField = value
                    Me.RaisePropertyChanged("Photo")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GuruMataPelajaranModel", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class GuruMataPelajaranModel
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private IdField As Integer
        
        Private MataPelajaranIdField As Integer
        
        Private GuruIdField As Integer
        
        Private CrudField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Id() As Integer
            Get
                Return Me.IdField
            End Get
            Set
                If (Me.IdField.Equals(value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property MataPelajaranId() As Integer
            Get
                Return Me.MataPelajaranIdField
            End Get
            Set
                If (Me.MataPelajaranIdField.Equals(value) <> true) Then
                    Me.MataPelajaranIdField = value
                    Me.RaisePropertyChanged("MataPelajaranId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=2)>  _
        Public Property GuruId() As Integer
            Get
                Return Me.GuruIdField
            End Get
            Set
                If (Me.GuruIdField.Equals(value) <> true) Then
                    Me.GuruIdField = value
                    Me.RaisePropertyChanged("GuruId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=3)>  _
        Public Property Crud() As Integer
            Get
                Return Me.CrudField
            End Get
            Set
                If (Me.CrudField.Equals(value) <> true) Then
                    Me.CrudField = value
                    Me.RaisePropertyChanged("Crud")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="GuruServiceReference.MasterGuruServiceSoap")>  _
    Public Interface MasterGuruServiceSoap
        
        'CODEGEN: Generating message contract since element name GetAllGuruResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetAllGuru", ReplyAction:="*")>  _
        Function GetAllGuru(ByVal request As GuruServiceReference.GetAllGuruRequest) As GuruServiceReference.GetAllGuruResponse
        
        'CODEGEN: Generating message contract since element name GetGuruResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetGuru", ReplyAction:="*")>  _
        Function GetGuru(ByVal request As GuruServiceReference.GetGuruRequest) As GuruServiceReference.GetGuruResponse
        
        'CODEGEN: Generating message contract since element name mguru from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SaveGuru", ReplyAction:="*")>  _
        Function SaveGuru(ByVal request As GuruServiceReference.SaveGuruRequest) As GuruServiceReference.SaveGuruResponse
        
        'CODEGEN: Generating message contract since element name mguru from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UpdateGuru", ReplyAction:="*")>  _
        Function UpdateGuru(ByVal request As GuruServiceReference.UpdateGuruRequest) As GuruServiceReference.UpdateGuruResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/DeleteGuru", ReplyAction:="*")>  _
        Sub DeleteGuru(ByVal recordId As Integer)
        
        'CODEGEN: Generating message contract since element name mguru from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SubmitGuruMataPelajaran", ReplyAction:="*")>  _
        Function SubmitGuruMataPelajaran(ByVal request As GuruServiceReference.SubmitGuruMataPelajaranRequest) As GuruServiceReference.SubmitGuruMataPelajaranResponse
        
        'CODEGEN: Generating message contract since element name GetGuruByMataPelajaranTahunAjaranResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetGuruByMataPelajaranTahunAjaran", ReplyAction:="*")>  _
        Function GetGuruByMataPelajaranTahunAjaran(ByVal request As GuruServiceReference.GetGuruByMataPelajaranTahunAjaranRequest) As GuruServiceReference.GetGuruByMataPelajaranTahunAjaranResponse
        
        'CODEGEN: Generating message contract since element name namaGuru from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetGuruByName", ReplyAction:="*")>  _
        Function GetGuruByName(ByVal request As GuruServiceReference.GetGuruByNameRequest) As GuruServiceReference.GetGuruByNameResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetAllGuruRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetAllGuru", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As GuruServiceReference.GetAllGuruRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As GuruServiceReference.GetAllGuruRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class GetAllGuruRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetAllGuruResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetAllGuruResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As GuruServiceReference.GetAllGuruResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As GuruServiceReference.GetAllGuruResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetAllGuruResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetAllGuruResult() As GuruServiceReference.GuruModel
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetAllGuruResult() As GuruServiceReference.GuruModel)
            MyBase.New
            Me.GetAllGuruResult = GetAllGuruResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetGuruRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetGuru", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As GuruServiceReference.GetGuruRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As GuruServiceReference.GetGuruRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetGuruRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public id As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal id As Integer)
            MyBase.New
            Me.id = id
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetGuruResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetGuruResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As GuruServiceReference.GetGuruResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As GuruServiceReference.GetGuruResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetGuruResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetGuruResult As GuruServiceReference.GuruModel
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetGuruResult As GuruServiceReference.GuruModel)
            MyBase.New
            Me.GetGuruResult = GetGuruResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SaveGuruRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SaveGuru", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As GuruServiceReference.SaveGuruRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As GuruServiceReference.SaveGuruRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SaveGuruRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public mguru As GuruServiceReference.GuruModel
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal mguru As GuruServiceReference.GuruModel)
            MyBase.New
            Me.mguru = mguru
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SaveGuruResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SaveGuruResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As GuruServiceReference.SaveGuruResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As GuruServiceReference.SaveGuruResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class SaveGuruResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UpdateGuruRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UpdateGuru", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As GuruServiceReference.UpdateGuruRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As GuruServiceReference.UpdateGuruRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class UpdateGuruRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public mguru As GuruServiceReference.GuruModel
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal mguru As GuruServiceReference.GuruModel)
            MyBase.New
            Me.mguru = mguru
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UpdateGuruResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UpdateGuruResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As GuruServiceReference.UpdateGuruResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As GuruServiceReference.UpdateGuruResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class UpdateGuruResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SubmitGuruMataPelajaranRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SubmitGuruMataPelajaran", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As GuruServiceReference.SubmitGuruMataPelajaranRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As GuruServiceReference.SubmitGuruMataPelajaranRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SubmitGuruMataPelajaranRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public mguru() As GuruServiceReference.GuruMataPelajaranModel
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal mguru() As GuruServiceReference.GuruMataPelajaranModel)
            MyBase.New
            Me.mguru = mguru
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SubmitGuruMataPelajaranResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SubmitGuruMataPelajaranResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As GuruServiceReference.SubmitGuruMataPelajaranResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As GuruServiceReference.SubmitGuruMataPelajaranResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class SubmitGuruMataPelajaranResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetGuruByMataPelajaranTahunAjaranRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetGuruByMataPelajaranTahunAjaran", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As GuruServiceReference.GetGuruByMataPelajaranTahunAjaranRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As GuruServiceReference.GetGuruByMataPelajaranTahunAjaranRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetGuruByMataPelajaranTahunAjaranRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public matapelajaranid As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public tahun As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal matapelajaranid As Integer, ByVal tahun As Integer)
            MyBase.New
            Me.matapelajaranid = matapelajaranid
            Me.tahun = tahun
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetGuruByMataPelajaranTahunAjaranResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetGuruByMataPelajaranTahunAjaranResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As GuruServiceReference.GetGuruByMataPelajaranTahunAjaranResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As GuruServiceReference.GetGuruByMataPelajaranTahunAjaranResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetGuruByMataPelajaranTahunAjaranResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetGuruByMataPelajaranTahunAjaranResult() As GuruServiceReference.GuruModel
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetGuruByMataPelajaranTahunAjaranResult() As GuruServiceReference.GuruModel)
            MyBase.New
            Me.GetGuruByMataPelajaranTahunAjaranResult = GetGuruByMataPelajaranTahunAjaranResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetGuruByNameRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetGuruByName", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As GuruServiceReference.GetGuruByNameRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As GuruServiceReference.GetGuruByNameRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetGuruByNameRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public namaGuru As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal namaGuru As String)
            MyBase.New
            Me.namaGuru = namaGuru
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetGuruByNameResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetGuruByNameResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As GuruServiceReference.GetGuruByNameResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As GuruServiceReference.GetGuruByNameResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetGuruByNameResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetGuruByNameResult() As GuruServiceReference.GuruModel
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetGuruByNameResult() As GuruServiceReference.GuruModel)
            MyBase.New
            Me.GetGuruByNameResult = GetGuruByNameResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface MasterGuruServiceSoapChannel
        Inherits GuruServiceReference.MasterGuruServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class MasterGuruServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of GuruServiceReference.MasterGuruServiceSoap)
        Implements GuruServiceReference.MasterGuruServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function GuruServiceReference_MasterGuruServiceSoap_GetAllGuru(ByVal request As GuruServiceReference.GetAllGuruRequest) As GuruServiceReference.GetAllGuruResponse Implements GuruServiceReference.MasterGuruServiceSoap.GetAllGuru
            Return MyBase.Channel.GetAllGuru(request)
        End Function
        
        Public Function GetAllGuru() As GuruServiceReference.GuruModel()
            Dim inValue As GuruServiceReference.GetAllGuruRequest = New GuruServiceReference.GetAllGuruRequest()
            inValue.Body = New GuruServiceReference.GetAllGuruRequestBody()
            Dim retVal As GuruServiceReference.GetAllGuruResponse = CType(Me,GuruServiceReference.MasterGuruServiceSoap).GetAllGuru(inValue)
            Return retVal.Body.GetAllGuruResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function GuruServiceReference_MasterGuruServiceSoap_GetGuru(ByVal request As GuruServiceReference.GetGuruRequest) As GuruServiceReference.GetGuruResponse Implements GuruServiceReference.MasterGuruServiceSoap.GetGuru
            Return MyBase.Channel.GetGuru(request)
        End Function
        
        Public Function GetGuru(ByVal id As Integer) As GuruServiceReference.GuruModel
            Dim inValue As GuruServiceReference.GetGuruRequest = New GuruServiceReference.GetGuruRequest()
            inValue.Body = New GuruServiceReference.GetGuruRequestBody()
            inValue.Body.id = id
            Dim retVal As GuruServiceReference.GetGuruResponse = CType(Me,GuruServiceReference.MasterGuruServiceSoap).GetGuru(inValue)
            Return retVal.Body.GetGuruResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function GuruServiceReference_MasterGuruServiceSoap_SaveGuru(ByVal request As GuruServiceReference.SaveGuruRequest) As GuruServiceReference.SaveGuruResponse Implements GuruServiceReference.MasterGuruServiceSoap.SaveGuru
            Return MyBase.Channel.SaveGuru(request)
        End Function
        
        Public Sub SaveGuru(ByVal mguru As GuruServiceReference.GuruModel)
            Dim inValue As GuruServiceReference.SaveGuruRequest = New GuruServiceReference.SaveGuruRequest()
            inValue.Body = New GuruServiceReference.SaveGuruRequestBody()
            inValue.Body.mguru = mguru
            Dim retVal As GuruServiceReference.SaveGuruResponse = CType(Me,GuruServiceReference.MasterGuruServiceSoap).SaveGuru(inValue)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function GuruServiceReference_MasterGuruServiceSoap_UpdateGuru(ByVal request As GuruServiceReference.UpdateGuruRequest) As GuruServiceReference.UpdateGuruResponse Implements GuruServiceReference.MasterGuruServiceSoap.UpdateGuru
            Return MyBase.Channel.UpdateGuru(request)
        End Function
        
        Public Sub UpdateGuru(ByVal mguru As GuruServiceReference.GuruModel)
            Dim inValue As GuruServiceReference.UpdateGuruRequest = New GuruServiceReference.UpdateGuruRequest()
            inValue.Body = New GuruServiceReference.UpdateGuruRequestBody()
            inValue.Body.mguru = mguru
            Dim retVal As GuruServiceReference.UpdateGuruResponse = CType(Me,GuruServiceReference.MasterGuruServiceSoap).UpdateGuru(inValue)
        End Sub
        
        Public Sub DeleteGuru(ByVal recordId As Integer) Implements GuruServiceReference.MasterGuruServiceSoap.DeleteGuru
            MyBase.Channel.DeleteGuru(recordId)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function GuruServiceReference_MasterGuruServiceSoap_SubmitGuruMataPelajaran(ByVal request As GuruServiceReference.SubmitGuruMataPelajaranRequest) As GuruServiceReference.SubmitGuruMataPelajaranResponse Implements GuruServiceReference.MasterGuruServiceSoap.SubmitGuruMataPelajaran
            Return MyBase.Channel.SubmitGuruMataPelajaran(request)
        End Function
        
        Public Sub SubmitGuruMataPelajaran(ByVal mguru() As GuruServiceReference.GuruMataPelajaranModel)
            Dim inValue As GuruServiceReference.SubmitGuruMataPelajaranRequest = New GuruServiceReference.SubmitGuruMataPelajaranRequest()
            inValue.Body = New GuruServiceReference.SubmitGuruMataPelajaranRequestBody()
            inValue.Body.mguru = mguru
            Dim retVal As GuruServiceReference.SubmitGuruMataPelajaranResponse = CType(Me,GuruServiceReference.MasterGuruServiceSoap).SubmitGuruMataPelajaran(inValue)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function GuruServiceReference_MasterGuruServiceSoap_GetGuruByMataPelajaranTahunAjaran(ByVal request As GuruServiceReference.GetGuruByMataPelajaranTahunAjaranRequest) As GuruServiceReference.GetGuruByMataPelajaranTahunAjaranResponse Implements GuruServiceReference.MasterGuruServiceSoap.GetGuruByMataPelajaranTahunAjaran
            Return MyBase.Channel.GetGuruByMataPelajaranTahunAjaran(request)
        End Function
        
        Public Function GetGuruByMataPelajaranTahunAjaran(ByVal matapelajaranid As Integer, ByVal tahun As Integer) As GuruServiceReference.GuruModel()
            Dim inValue As GuruServiceReference.GetGuruByMataPelajaranTahunAjaranRequest = New GuruServiceReference.GetGuruByMataPelajaranTahunAjaranRequest()
            inValue.Body = New GuruServiceReference.GetGuruByMataPelajaranTahunAjaranRequestBody()
            inValue.Body.matapelajaranid = matapelajaranid
            inValue.Body.tahun = tahun
            Dim retVal As GuruServiceReference.GetGuruByMataPelajaranTahunAjaranResponse = CType(Me,GuruServiceReference.MasterGuruServiceSoap).GetGuruByMataPelajaranTahunAjaran(inValue)
            Return retVal.Body.GetGuruByMataPelajaranTahunAjaranResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function GuruServiceReference_MasterGuruServiceSoap_GetGuruByName(ByVal request As GuruServiceReference.GetGuruByNameRequest) As GuruServiceReference.GetGuruByNameResponse Implements GuruServiceReference.MasterGuruServiceSoap.GetGuruByName
            Return MyBase.Channel.GetGuruByName(request)
        End Function
        
        Public Function GetGuruByName(ByVal namaGuru As String) As GuruServiceReference.GuruModel()
            Dim inValue As GuruServiceReference.GetGuruByNameRequest = New GuruServiceReference.GetGuruByNameRequest()
            inValue.Body = New GuruServiceReference.GetGuruByNameRequestBody()
            inValue.Body.namaGuru = namaGuru
            Dim retVal As GuruServiceReference.GetGuruByNameResponse = CType(Me,GuruServiceReference.MasterGuruServiceSoap).GetGuruByName(inValue)
            Return retVal.Body.GetGuruByNameResult
        End Function
    End Class
End Namespace
